# Generated by Django 4.1 on 2022-09-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_watchlistitem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='release_date',
            field=models.DateField(),
        ),
    ]
